### ISSUE TITLE
Provide the ability to switch the button text at the same time as the display

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/o-toggle#70]
Feature Request:

## What
When a button is used as the visibility trigger its text doesn't change to reflect the visibility of the toggled area.

## Details
I have a 'Show Filters' button which toggles the display of a form containing set of radio buttons. See here https://risks.in.ft.com/
When toggled the form appears but the toggle continues to be named 'Show Filters'. It should have switched to be 'Hide Filters'.
Could we add 'toggle-to-visible-text' and 'toggle-to-hide-text' or similar as properties to o-toggle?

## Additional information
I can consider o-expander but I've not seen that used with the nice o-button styles for the toggle.

**Comment by notlee** [comment]
hey @GeoffThorpeFT, you might find [o-expander](https://registry.origami.ft.com/components/o-expander@5.0.11/readme?brand=master#hidden-expander) a better fit for your usecase since it already has the functionality to update target text? There's an o-expander option to hide/show in a similar way to `o-toggle`. I'm not sure why both exist, we have an [issue open to look at deprecating o-toggle](https://github.com/Financial-Times/o-toggle/issues/33) in favour of `o-expander`.

**Comment by GeoffThorpeFT** [comment]
Thanks @notlee I'll raise an issue against our code to try the switch to o-expander.

**Comment by JakeChampion** [comment]
I'll close this issue as the solution is to use `o-expander` 👍
